# Generated by Django 2.2 on 2019-09-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='venue', max_length=200),
            preserve_default=False,
        ),
    ]
