# Generated by Django 2.2 on 2019-09-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0005_event_catetgories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='catetgories',
            new_name='categories',
        ),
    ]
